## Cache the result of calculating the inverse of a matrix. 
## --------------------------------------------------------
## Calculating matrix inversion is a costly computational process. These functions
## allow the user to create an object which stores a matrix and can cache its inverse. 
## The function makeCacheMatrix creates the matrix object, and the function 
## cacheSolve either retrieves the cached inverse from the matrix object or 
## calculates and stores the inverse if the inverse has not yet been calculated.

## Description: 
## Returns a list containing a matrix and the ability to cache the value of its
## inverse. See cacheSolve. The ellipsis argument is intended for backwards 
## compatibility in future versions. 
##
## Usage: makeCachMatrix()
## Arguments: 
##  x: the matrix to be cached. Defaults to an empty matrix
##  ...: Unused. 
##
## Value:
##  A list with the following properties: 
##    set: A function which sets the value of the stored matrix
##    get: A function which returns the value of the stored matrix
##    setInverse: A function which sets the value of the cached inverse
##    getInverse: A function which gets the value of the cached inverse
##
## Note:
##  The setInverse function is designed to be used by the cacheSolve function
##  which sets the cached value when it is first called with an object returned by
##  makeCacheMatrix.

makeCacheMatrix <- function(x = matrix()) {
  inverse <- NULL
  set <- function(newMatrix){
    x <<- newMatrix
    inverse <<- NULL
  }
  get <- function() x 
  setInverse <- function(inv) inverse <<- inv
  getInverse <- function() inverse
  list(
        set = set
      , get = get
      , setInverse = setInverse
      , getInverse = getInverse
      )
}

##  Description:
##    Accepts an object (x) constructed using makeCacheMatrix and returns its
##    inverse. 
##
##  Usage:
##    cacheSolve(x = myCacheMatrix)
##
##  Arguments:
##    x: List generated by makeCacheMatrix()
##    ...: Unused.
##
##  Details:
##    This function accepts a single argument which it expects to be a list 
##    generated by the makeCacheMatrix function. The ellipsis argument is 
##    present for backward compatibility in future versions.
##    Returns the inverse of the matrix stored in x. If the inverse has not yet
##    been calculated it will cache the inverse in x. Future
##    calls to cacheSolve with x will then return the cached value. 

cacheSolve <- function(x, ...) {
  inverse <- x$getInverse()
  if(!is.null(inverse)){
    message("fetching cached inverse")
    return(inverse)
  }
  mat <- x$get()
  inv <- solve(mat)
  x$setInverse(inv)
  inv
}
